// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProplanetReplicationTool.Data;

#nullable disable

namespace ProplanetReplicationTool.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250318120729_RemoveSBTestMaterialRelation")]
    partial class RemoveSBTestMaterialRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProplanetReplicationTool.Data.Models.EcosystemToxicity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("Air")
                        .HasColumnType("real")
                        .HasColumnName("air");

                    b.Property<float>("AquaticFreshwater")
                        .HasColumnType("real")
                        .HasColumnName("aquatic_freshwater");

                    b.Property<float>("AquaticMarinewater")
                        .HasColumnType("real")
                        .HasColumnName("aquatic_marinewater");

                    b.Property<float>("AquaticSedimentFreshwater")
                        .HasColumnType("real")
                        .HasColumnName("aquatic_sediment_freshwater");

                    b.Property<float>("AquaticSedimentMarinewater")
                        .HasColumnType("real")
                        .HasColumnName("aquatic_sediment_marinewater");

                    b.Property<float>("AquaticStp")
                        .HasColumnType("real")
                        .HasColumnName("aquatic_stp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<float>("PredatorsOralPoisoning")
                        .HasColumnType("real")
                        .HasColumnName("predators_oral_poisoning");

                    b.Property<float>("TerrestrialSoil")
                        .HasColumnType("real")
                        .HasColumnName("terrestrial_soil");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId")
                        .IsUnique();

                    b.ToTable("ecosystem_toxicities");
                });

            modelBuilder.Entity("ProplanetReplicationTool.Data.Models.HumanToxicity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<float>("PDermalLocalLong")
                        .HasColumnType("real")
                        .HasColumnName("p_dermal_local_long");

                    b.Property<float>("PDermalLocalShort")
                        .HasColumnType("real")
                        .HasColumnName("p_dermal_local_short");

                    b.Property<float>("PDermalSystemicLong")
                        .HasColumnType("real")
                        .HasColumnName("p_dermal_systemic_long");

                    b.Property<float>("PDermalSystemicShort")
                        .HasColumnType("real")
                        .HasColumnName("p_dermal_systemic_short");

                    b.Property<float>("PEyesLocal")
                        .HasColumnType("real")
                        .HasColumnName("p_eyes_local");

                    b.Property<float>("PInhalationLocalLong")
                        .HasColumnType("real")
                        .HasColumnName("p_inhalation_local_long");

                    b.Property<float>("PInhalationLocalShort")
                        .HasColumnType("real")
                        .HasColumnName("p_inhalation_local_short");

                    b.Property<float>("PInhalationSystemicLong")
                        .HasColumnType("real")
                        .HasColumnName("p_inhalation_systemic_long");

                    b.Property<float>("PInhalationSystemicShort")
                        .HasColumnType("real")
                        .HasColumnName("p_inhalation_systemic_short");

                    b.Property<float>("POralSystemicLong")
                        .HasColumnType("real")
                        .HasColumnName("p_oral_systemic_long");

                    b.Property<float>("POralSystemicShort")
                        .HasColumnType("real")
                        .HasColumnName("p_oral_systemic_short");

                    b.Property<float>("WDermalLocalLong")
                        .HasColumnType("real")
                        .HasColumnName("w_dermal_local_long");

                    b.Property<float>("WDermalLocalShort")
                        .HasColumnType("real")
                        .HasColumnName("w_dermal_local_short");

                    b.Property<float>("WDermalSystemicLong")
                        .HasColumnType("real")
                        .HasColumnName("w_dermal_systemic_long");

                    b.Property<float>("WDermalSystemicShort")
                        .HasColumnType("real")
                        .HasColumnName("w_dermal_systemic_short");

                    b.Property<float>("WEyesLocal")
                        .HasColumnType("real")
                        .HasColumnName("w_eyes_local");

                    b.Property<float>("WInhalationLocalLong")
                        .HasColumnType("real")
                        .HasColumnName("w_inhalation_local_long");

                    b.Property<float>("WInhalationLocalShort")
                        .HasColumnType("real")
                        .HasColumnName("w_inhalation_local_short");

                    b.Property<float>("WInhalationSystemicLong")
                        .HasColumnType("real")
                        .HasColumnName("w_inhalation_systemic_long");

                    b.Property<float>("WInhalationSystemicShort")
                        .HasColumnType("real")
                        .HasColumnName("w_inhalation_systemic_short");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId")
                        .IsUnique();

                    b.ToTable("human_toxicities");
                });

            modelBuilder.Entity("ProplanetReplicationTool.Data.Models.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cas")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cas");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("formula");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("MolecularWeight")
                        .HasColumnType("real")
                        .HasColumnName("molecular_weight");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("TotalCarbonAtoms")
                        .HasColumnType("integer")
                        .HasColumnName("total_carbon_atoms");

                    b.HasKey("Id");

                    b.ToTable("materials");
                });

            modelBuilder.Entity("ProplanetReplicationTool.Data.Models.RinaTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Distance")
                        .HasColumnType("real")
                        .HasColumnName("distance");

                    b.Property<float>("InteractionEnergy")
                        .HasColumnType("real")
                        .HasColumnName("interaction_energy");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("LogKow")
                        .HasColumnType("real")
                        .HasColumnName("log_kow");

                    b.Property<float>("LogPow")
                        .HasColumnType("real")
                        .HasColumnName("log_pow");

                    b.Property<float>("LumoHomo")
                        .HasColumnType("real")
                        .HasColumnName("lumo_homo");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<float>("Toxicity")
                        .HasColumnType("real")
                        .HasColumnName("toxicity");

                    b.Property<float>("Wca")
                        .HasColumnType("real")
                        .HasColumnName("wca");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId")
                        .IsUnique();

                    b.ToTable("rina_tests");
                });

            modelBuilder.Entity("ProplanetReplicationTool.Data.Models.SBTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.HasKey("Id");

                    b.ToTable("sb_tests");
                });

            modelBuilder.Entity("ProplanetReplicationTool.Data.Models.SBTestInput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("EmissionToAgriculturalSoilContinental")
                        .HasColumnType("real")
                        .HasColumnName("continental_emission_agricultural_soil");

                    b.Property<float>("EmissionToAgriculturalSoilRegional")
                        .HasColumnType("real")
                        .HasColumnName("regional_emission_agricultural_soil");

                    b.Property<float>("EmissionToAirArctic")
                        .HasColumnType("real")
                        .HasColumnName("artic_emission_air");

                    b.Property<float>("EmissionToAirContinental")
                        .HasColumnType("real")
                        .HasColumnName("continental_emission_air");

                    b.Property<float>("EmissionToAirModerate")
                        .HasColumnType("real")
                        .HasColumnName("moderate_emission_air");

                    b.Property<float>("EmissionToAirRegional")
                        .HasColumnType("real")
                        .HasColumnName("regional_emission_air");

                    b.Property<float>("EmissionToAirTropical")
                        .HasColumnType("real")
                        .HasColumnName("tropical_emission_air");

                    b.Property<float>("EmissionToFreshWaterContinental")
                        .HasColumnType("real")
                        .HasColumnName("continental_emission_water1");

                    b.Property<float>("EmissionToFreshWaterRegional")
                        .HasColumnType("real")
                        .HasColumnName("regional_emission_water1");

                    b.Property<float>("EmissionToLakeWaterContinental")
                        .HasColumnType("real")
                        .HasColumnName("continental_emission_water0");

                    b.Property<float>("EmissionToLakeWaterRegional")
                        .HasColumnType("real")
                        .HasColumnName("regional_emission_water0");

                    b.Property<float>("EmissionToNaturalSoilContinental")
                        .HasColumnType("real")
                        .HasColumnName("continental_emission_natural_soil");

                    b.Property<float>("EmissionToNaturalSoilRegional")
                        .HasColumnType("real")
                        .HasColumnName("regional_emission_natural_soil");

                    b.Property<float>("EmissionToOtherSoilContinental")
                        .HasColumnType("real")
                        .HasColumnName("continental_emission_other_soil");

                    b.Property<float>("EmissionToOtherSoilRegional")
                        .HasColumnType("real")
                        .HasColumnName("regional_emission_other_soil");

                    b.Property<float>("EmissionToSeaWaterContinental")
                        .HasColumnType("real")
                        .HasColumnName("continental_emission_water2");

                    b.Property<float>("EmissionToSeaWaterRegional")
                        .HasColumnType("real")
                        .HasColumnName("regional_emission_water2");

                    b.Property<float>("EmissionToSoilArctic")
                        .HasColumnType("real")
                        .HasColumnName("artic_emission_soil");

                    b.Property<float>("EmissionToSoilModerate")
                        .HasColumnType("real")
                        .HasColumnName("moderate_emission_soil");

                    b.Property<float>("EmissionToSoilTropical")
                        .HasColumnType("real")
                        .HasColumnName("tropical_emission_soil");

                    b.Property<float>("EmissionToWaterArctic")
                        .HasColumnType("real")
                        .HasColumnName("artic_emission_water2");

                    b.Property<float>("EmissionToWaterModerate")
                        .HasColumnType("real")
                        .HasColumnName("moderate_emission_water2");

                    b.Property<float>("EmissionToWaterTropical")
                        .HasColumnType("real")
                        .HasColumnName("tropical_emission_water2");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fingerprint");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("MolecularWeight")
                        .HasColumnType("real")
                        .HasColumnName("molecular_weight");

                    b.Property<string>("NanomaterialName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nanomaterial_name");

                    b.Property<Guid>("SBTestId")
                        .HasColumnType("uuid")
                        .HasColumnName("sb_test_id");

                    b.Property<string>("ScenarioName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scenario_name");

                    b.HasKey("Id");

                    b.HasIndex("SBTestId")
                        .IsUnique();

                    b.ToTable("sb_tests_inputs");
                });

            modelBuilder.Entity("ProplanetReplicationTool.Data.Models.EcosystemToxicity", b =>
                {
                    b.HasOne("ProplanetReplicationTool.Data.Models.Material", "Material")
                        .WithOne("EcosystemToxicity")
                        .HasForeignKey("ProplanetReplicationTool.Data.Models.EcosystemToxicity", "MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("ProplanetReplicationTool.Data.Models.HumanToxicity", b =>
                {
                    b.HasOne("ProplanetReplicationTool.Data.Models.Material", "Material")
                        .WithOne("HumanToxicity")
                        .HasForeignKey("ProplanetReplicationTool.Data.Models.HumanToxicity", "MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("ProplanetReplicationTool.Data.Models.RinaTest", b =>
                {
                    b.HasOne("ProplanetReplicationTool.Data.Models.Material", "Material")
                        .WithOne("RinaTest")
                        .HasForeignKey("ProplanetReplicationTool.Data.Models.RinaTest", "MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("ProplanetReplicationTool.Data.Models.SBTestInput", b =>
                {
                    b.HasOne("ProplanetReplicationTool.Data.Models.SBTest", "SBTest")
                        .WithOne("SBTestInput")
                        .HasForeignKey("ProplanetReplicationTool.Data.Models.SBTestInput", "SBTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SBTest");
                });

            modelBuilder.Entity("ProplanetReplicationTool.Data.Models.Material", b =>
                {
                    b.Navigation("EcosystemToxicity")
                        .IsRequired();

                    b.Navigation("HumanToxicity")
                        .IsRequired();

                    b.Navigation("RinaTest")
                        .IsRequired();
                });

            modelBuilder.Entity("ProplanetReplicationTool.Data.Models.SBTest", b =>
                {
                    b.Navigation("SBTestInput")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
